// action types

export const START_TEST = 'START_TEST';
export const START_TEST_SUCCESS = 'START_TEST_SUCCESS';
export const START_TEST_FAILURE = 'START_TEST_FAILURE';

export const FETCH_TODAYS_TRENDING_MOVIES_START =
  'FETCH_TODAYS_TRENDING_MOVIES_START';
export const FETCH_TODAYS_TRENDING_MOVIES_SUCCESS =
  'FETCH_TODAYS_TRENDING_MOVIES_SUCCESS';
export const FETCH_TODAYS_TRENDING_MOVIES_FAILURE =
  'FETCH_TODAYS_TRENDING_MOVIES_FAILURE';
