// action types

// reset the stored movie array to be empty when first loading component
export const CREATE_FRESH_MOVIE_ARRAY_ON_MOUNT =
  'CREATE_FRESH_MOVIE_ARRAY_ON_MOUNT';

// for searching specific movies
export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

// for the filtering of specific aggregations of movies
export const FETCH_POPULAR_MOVIES_START = 'FETCH_POPULAR_MOVIES_START';
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
export const FETCH_POPULAR_MOVIES_FAILURE = 'FETCH_POPULAR_MOVIES_FAILURE';

export const FETCH_TOP_RATED_MOVIES_START = 'FETCH_TOP_RATED_MOVIES_START';
export const FETCH_TOP_RATED_MOVIES_SUCCESS = 'FETCH_TOP_RATED_MOVIES_SUCCESS';
export const FETCH_TOP_RATED_MOVIES_FAILURE = 'FETCH_TOP_RATED_MOVIES_FAILURE';

export const FETCH_TRENDING_MOVIES_START = 'FETCH_TRENDING_MOVIES_START';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export const FETCH_TRENDING_MOVIES_FAILURE = 'FETCH_TRENDING_MOVIES_FAILURE';

// setting which aggregation of movies should be shown
export const SET_VISIBILITY_FILTER_POPULAR = 'SET_VISIBILITY_FILTER_POPULAR';
export const SET_VISIBILITY_FILTER_TOP_RATED =
  'SET_VISIBILITY_FILTER_TOP_RATED';
export const SET_VISIBILITY_FILTER_TRENDING = 'SET_VISIBILITY_TRENDING';
export const SET_VISIBILITY_FILTER_SEARCHED = 'SET_VISIBILITY_FILTER_SEARCHED';
